# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: Bug Report
description: Report a bug in the project.
title: '[Bug] '
labels:
  - Bug
body:
  - id: description
    type: textarea
    attributes:
      label: Description
      description: A short description of the bug.
    validations:
      required: true
  - id: steps
    type: textarea
    attributes:
      label: Steps to Reproduce
      description: Please provide a set of steps to reproduce the issue.
    validations:
      required: true
  - id: expected-behaviour
    type: textarea
    attributes:
      label: Expected Behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - id: actual-behaviour
    type: textarea
    attributes:
      label: Actual Behaviour
      description: A clear and concise description of what actually happened.
    validations:
      required: true
  - id: operating-system
    type: dropdown
    attributes:
      label: Operating System
      description: The operating system you are using.
      options:
        - Windows
        - macOS
        - Linux
        - Other (Please state in "Additional Details")
    validations:
      required: true
  - id: mod-version
    type: input
    attributes:
      label: Mod Version
      description: The version of the mod you are using.
    validations:
      required: true
  - id: additional-details
    type: textarea
    attributes:
      label: Additional Details
      description: Any additional information that may be helpful in solving the issue.
    validations:
      required: false
  - id: disclaimers
    type: checkboxes
    attributes:
      label: Disclaimer
      description: 'By submitting this issue, you state the following:'
      options:
        - label: I have searched for existing issues and this is not a duplicate.
          required: true
        - label: I have read the project's contributing guidelines.
          required: true
        - label: I have read and understood the project's code of conduct.
          required: true
